### ISSUE TITLE
Add --join

### ISSUE THREAD

**Issue by esamattis** [TrevorBurnham/Jitter#10]
How about adding --join like in coffee-command so that selected files will be compiled in to a single file with a single namespace?

**Comment by TrevorBurnham** [comment]
Currently, Jitter supports running all tests in a directory after each change; if any more post-change hooks were added, the complexity of the tool would go up exponentially. I learned this the hard way by trying (and, so far, failing) to write another, more robust CoffeeScript build toolstill on my to-do list, but it's a hard problem.

Here's why this is so hard:

Let's say you enable both tests and concatenation. Which do you want to do first? Well, the tests might depend on the concatenated file, so we have to do concatenation, wait for that to finish, then run the tests. But what if the source files change a second time during concatenation? The ideal behavior would be to abort the concatenation and restart it. What if the source files change again during the tests? If you support concatenation, people will also want minification. Now you've got four things (compilation, concatenation, minification, testing) that have to happen, in order, every time a file changesand additional source file changes could occur at any point in that pipeline.

Don't get me wrong, CoffeeScript needs a tool that can do this (right now, your best option is to write a Cakefile for your project), but Jitter should stay simple.

**Comment by MarioRicalde** [comment]
This is absolute?

I thought this was the perfect tool to work side by side with SASS / Compass on a stand-alone project, but concatenation is one thing I'm trying to get for the [Arrangement for View Assets Pattern](https://github.com/kuroir/AVA-Pattern).

Have you found any other service that can provide the concatenation functionality? the idea would be to just simply concatenate the files without needed minifying.

**Comment by TrevorBurnham** [comment]
Sorry, kuroir; it's just not in the cards. You should write a Cakefile to do this for your project, or use a tool like Sprockets 2 (which lets you specify dependencies in comments and then concatenate the compiled JS in that order).
