### ISSUE TITLE
Better intro

### ISSUE THREAD

**Issue by AriaMinaei** [TrevorBurnham/Jitter#27]
It takes a while to get watching/testing/maps running with other tools. Jitter is perhaps the fastest way to get a project started with CoffeeScript. We should mention that in the intro.

**Comment by TrevorBurnham** [comment]
That feels like slightly too bold a claim for Jitter. It does a handful of things that `coffee -cw` doesn't do, but I wouldn't say that it's easier to set up in general. And for most projects, I'd recommend setting up a build process with [Grunt](http://gruntjs.com/).
