### ISSUE TITLE
Add notify-send support

### ISSUE THREAD

**Issue by balazstth** [TrevorBurnham/Jitter#3]
A suggestion rather than an issue: consider wiring in _notify-send_ for Linux. The changes needed would be trivial.
See: http://manpages.ubuntu.com/manpages/maverick/man1/notify-send.1.html

**Comment by TrevorBurnham** [comment]
This is a nice suggestion, but as a Mac person, it's not a priority for me / I don't have any easy way of testing it. If you submit a patch, I'll happily accept it.
