### ISSUE TITLE
Calling jitter('src', 'lib') from a node module results in error saying "object is not a function"

### ISSUE THREAD

**Issue by anishdeena** [TrevorBurnham/Jitter#32]
I have the following lines in my server.js:

var jitter = require('jitter');
jitter('coffee', 'js'); //where coffee is the source dir and js is the target dir.

The last line results in an error saying "object is not a function". Please help.

**Comment by TrevorBurnham** [comment]
Sorry for the delay in responding. Yes, you're right: Jitter supported usage from JS as of the commit that added those lines to the README (0b164d6d43f811508f3d78b8e8f08dc16efda8b8), but not anymore. If you'd like to reintroduce that functionality, feel free to submit a PR. For now, I'm just going to remove the inaccurate section of the README.
