### ISSUE TITLE
jitter is broken with node 0.4.1 / npm 0.3.1

### ISSUE THREAD

**Issue by rmoriz** [TrevorBurnham/Jitter#4]
due to dep. to sink, which is broken:

info fetch http://registry.npmjs.org/sink/-/sink-0.1.0.tgz
npm ERR! couldn't read package.json in /tmp/npm-1298834509217/1298834509217-0.8205640104133636/contents/package
npm ERR! Error installing sink@0.1.0
npm ERR! Error: Failed to parse json
npm ERR! Unexpected token ILLEGAL
npm ERR!     at jsonParseFail (/opt/local/lib/node/.npm/npm/0.3.9/package/lib/utils/read-json.js:89:11)
npm ERR!     at /opt/local/lib/node/.npm/npm/0.3.9/package/lib/utils/read-json.js:82:14
npm ERR!     at P (/opt/local/lib/node/.npm/npm/0.3.9/package/lib/utils/read-json.js:62:40)
npm ERR!     at cb (/opt/local/lib/node/.npm/npm/0.3.9/package/lib/utils/graceful-fs.js:31:9)
npm ERR!     at [object Object].<anonymous> (fs.js:86:5)
npm ERR!     at [object Object].emit (events.js:39:17)
npm ERR!     at afterRead (fs.js:843:12)
npm ERR! JSON.parse 
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse Note that package.json must be actual JSON, not
npm ERR! JSON.parse just a JavaScript object.
npm ERR! JSON.parse 
npm ERR! JSON.parse This changed in npm 0.3.0, and is not a bug in npm.
npm ERR! JSON.parse Tell the package author to fix their package.json file.
npm ERR! JSON.parse

**Comment by TrevorBurnham** [comment]
Hmm, I'm on node 0.4.1 and npm 0.2.18, and I have no issues when I run `npm install sink`. So it sounds like something changed in the new version of npm that makes sink's package.json incompatible. I see that you've raised an issue for sink [here](https://github.com/hiddenbek/sink/issues#issue/2). I don't see any obvious problems with sink's [package.json](https://github.com/hiddenbek/sink/issues#issue/2)... my kingdom for a line number!

**Comment by rmoriz** [comment]
sink is now working, that means jitter works, too ;-)
https://github.com/hiddenbek/sink/issues/2

**Comment by dsrw** [comment]
I believe both sink and jitter had issues with package.json.  npm is now using a proper JSON parser for package.json, so double quotes are required for keys and strings.  I can't install jitter using npm 0.3.9, even after the sink fix.

I submitted a pull that removes single quotes from package.json, bumps the version number, and required the updated version of sink.

**Comment by TrevorBurnham** [comment]
Said pull request was merged in. npm is a harsh mistress: It's long refused to install anything without a semvar-compatible version number (e.g. 1.0.0 is valid but 1.0 isn't), and now it's refusing to install anything with single quotes in the JSON file. True, the JSON spec dictates double quotes, but still... harsh.

Anyway, thanks for bringing the issue to our attention, rmoriz.
